export const CAPABILITIES = [
  'COMMERCIAL_EDIT',
  'COMMERCIAL_APPROVE',
  'COMMERCIAL_CANCEL',
  'MARGIN_POLICY_MANAGE',
  'ACCESS_MANAGE',
  'OPERATIONS_EDIT',
  'FINANCE_EDIT',
  'FISCAL_EDIT',
  'RISK_MANAGE',
] as const;

export type Capability = (typeof CAPABILITIES)[number];
